version: '3.8'
services:
  db:
    image: postgres:15
    container_name: github_dashboard_db
    environment:
      POSTGRES_USER: elab_user
      POSTGRES_PASSWORD: elab_password
      POSTGRES_DB: github_stats
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    container_name: github_dashboard_backend
    env_file: ./backend/.env  # <--- OVA LINIJA JE KLJUČNA!
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
  frontend:
    build: ./frontend
    container_name: github_dashboard_frontend
    ports:
      - "3000:3000" # Prvi broj je ono što kucaš u browseru (localhost:3000)
    volumes:
      - ./frontend:/app
      - /app/node_modules # Ovo je bitno da Docker ne pregazi biblioteke tvojim lokalnim
    environment:
      - CHOKIDAR_USEPOLLING=true # Ovo osigurava da se sajt osveži čim sačuvaš kod u DataSpell-u
    depends_on:
      - backend

volumes:
  postgres_data: