version: '3.8'
services:
  db:
    image: postgres:15
    container_name: github_dashboard_db
    environment:
      POSTGRES_USER: elab_user
      POSTGRES_PASSWORD: elab_password
      POSTGRES_DB: github_stats
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./backend  # Ovo mora da pokazuje na folder gde je Dockerfile
    container_name: github_dashboard_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app # Ovo sinhronizuje kod sa kontejnerom
    depends_on:
      - db

volumes:
  postgres_data: